services:
  postgresql:
    image: postgres:alpine
    container_name: local_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: local_pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
  node-service:
    image: api-service
    container_name: local_api
    ports:
      - "3000:3000"
    depends_on:
      - postgresql